"""initial schema

Revision ID: 0b7f8aeed7fe
Revises: 
Create Date: 2026-09-21 22:49:34.932338
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0b7f8aeed7fe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('question_count > 0', name=op.f('ck_rounds_question_count_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_rounds_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rounds_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds'))
    )
    op.create_index('ix_rounds_user_id_started_at', 'rounds', ['user_id', 'started_at'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('situation_text', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', name='status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai', name='source', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 3', name=op.f('ck_scenarios_difficulty_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_scenarios_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios')),
    sa.UniqueConstraint('slug', name=op.f('uq_scenarios_slug'))
    )
    op.create_index('ix_scenarios_category_status', 'scenarios', ['category_id', 'status'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.String(length=300), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('position BETWEEN 1 AND 3', name=op.f('ck_choices_position_range')),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_choices_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_choices')),
    sa.UniqueConstraint('id', 'scenario_id', name='uq_choices_id_scenario_id'),
    sa.UniqueConstraint('scenario_id', 'position', name='uq_choices_scenario_id_position')
    )
    op.create_table('round_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('question_order >= 1', name=op.f('ck_round_questions_question_order_positive')),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_round_questions_round_id_rounds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_round_questions_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_round_questions')),
    sa.UniqueConstraint('round_id', 'question_order', name='uq_round_questions_round_id_order'),
    sa.UniqueConstraint('round_id', 'scenario_id', name='uq_round_questions_round_id_scenario_id')
    )
    op.create_table('round_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_key', sa.String(length=50), nullable=False),
    sa.Column('scoring_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_round_results_round_id_rounds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_round_results')),
    sa.UniqueConstraint('round_id', name=op.f('uq_round_results_round_id'))
    )
    op.create_table('user_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['choice_id', 'scenario_id'], ['choices.id', 'choices.scenario_id'], name='fk_user_answers_choice_in_scenario'),
    sa.ForeignKeyConstraint(['round_id', 'scenario_id'], ['round_questions.round_id', 'round_questions.scenario_id'], name='fk_user_answers_round_question', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_user_answers_round_id_rounds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_answers')),
    sa.UniqueConstraint('round_id', 'scenario_id', name='uq_user_answers_round_id_scenario_id')
    )
    op.create_index('ix_user_answers_scenario_id_choice_id', 'user_answers', ['scenario_id', 'choice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_answers_scenario_id_choice_id', table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_table('round_results')
    op.drop_table('round_questions')
    op.drop_table('choices')
    op.drop_index('ix_scenarios_category_status', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('ix_rounds_user_id_started_at', table_name='rounds')
    op.drop_table('rounds')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
